 # Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'LunchPicking' do
  

  # Pods for LunchPicking
  pod 'SnapKit', '~> 5.0.0'

  target 'LunchPickingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LunchPickingUITests' do
    # Pods for testing
  end

end
